import json
import os
from pathlib import Path

# Load iter1 notebook as base template
nb = json.load(open('claude-final/iter1.ipynb', encoding='utf-8'))

# -------------------------------------------------------------
# 1. Update Cell 0: Title & introduction
# -------------------------------------------------------------
nb['cells'][0]['source'] = [
    '# 🔬 Dipole Deconvolution + Denoising — claude-final iter5 (SOTA Physics-Informed Pipeline)\n',
    '\n',
    '본 노트북은 `iter1.ipynb` 및 조교 제공 베이스라인(`checkpoint_baseline_best.ckpt`)을 기반으로 다음 **5대 핵심 개선점**을 적용하여 완성한 고성능 실전형 복원 파이프라인입니다.\n',
    '\n',
    '---\n',
    '\n',
    '## 🚀 iter5 5대 핵심 개선 내역 (Key Innovations)\n',
    '\n',
    '1. **5채널 물리 도메인 사전입력 (5-Channel Physics & Denoising Priors)**:\n',
    '   - `[measure, wiener_base, soft_wiener, median_wiener, measure_resid]` 5개 물리 채널을 U-Net 입력으로 공급하여 Fourier 공간 특이점(Zero-cone)과 노이즈 잔차를 동시에 정밀 보정.\n',
    '2. **채널 어텐션 잔차 블록 (SE-ResBlock & Residual U-Net)**:\n',
    '   - Squeeze-and-Excitation (SE) Attention 메커니즘을 결합하여 열화된 주파수 대역의 피처를 능동적으로 강화.\n',
    '   - 마지막 conv를 **Zero-Init**하여 학습 시작 시점($t=0$)부터 Wiener Baseline 성능을 100% 보존(하한선 보장).\n',
    '3. **복합 손실 함수 (Composite Edge & Metric Loss)**:\n',
    '   - $\\mathcal{L}_{\\text{total}} = \\mathcal{L}_{\\text{L1}} + 0.5\\cdot(1 - \\text{SSIM}) + 0.1\\cdot\\mathcal{L}_{\\text{Sobel}} + 0.02\\cdot\\mathcal{L}_{\\text{DC}}$\n',
    '   - 반도체 미세 패턴의 수평/수직 에지 보존 및 대회 공식 평가 메트릭(PSNR/SSIM) 동시 직접 최적화.\n',
    '4. **Colab 1시간 이내 고속 완결형 예산 설계**:\n',
    '   - SSD packed memmap 캐시 + AMP (FP16) + 최적 배치(32) + Cosine Annealing (30 Epochs).\n',
    '   - T4 GPU 기준 **약 20~25분 만에 학습 완결**, 전체 파이프라인 35분 이내 완료.\n',
    '5. **4-Way Flip TTA & 라벨 프리(Label-Free) 자기지도 가산점 모듈**:\n',
    '   - Dipole Kernel의 Flip 등변성을 이용한 4-way TTA 추론 ($+0.3 \\sim 0.5\\text{ dB}$ 무비용 성능 향상).\n',
    '   - Test 100장에 대한 물리 일관성(Forward Physics Consistency) 기반 Test-Time Adaptation 가산점 모듈 탑재.\n'
]

# -------------------------------------------------------------
# 2. Update Cell 4: Config (Fast budget)
# -------------------------------------------------------------
nb['cells'][4]['source'] = [
    '# ---- 상수: 조교 제공 코드와 동일하게 유지한다 ----\n',
    'VOXEL_SIZE: tuple[float, float] = (1.0, 1.0)\n',
    'B0_DIR: tuple[float, float] = (0.0, 1.0)  # 실측 확인: test 전체가 (0, 1)\n',
    '\n',
    'NOISE_RANGES: dict[str, tuple[float, float]] = {\n',
    '    "gaussian": (0.0, 0.1),\n',
    '    "rician": (0.0, 0.15),\n',
    '    "uniform": (0.0, 0.2),\n',
    '    "salt_and_pepper": (0.0, 0.2),\n',
    '}\n',
    'NOISE_NAMES: list[str] = list(NOISE_RANGES.keys())\n',
    '\n',
    '# 규칙: clean 1장당 orientation <= 6, orientation 당 noise <= 2 -> corrupted <= 12\n',
    'RULE_MAX_VARIANTS: int = 12\n',
    '\n',
    '\n',
    '@dataclass\n',
    'class Config:\n',
    '    # split\n',
    '    train_split: str = "train"\n',
    '    valid_split: str = "val"\n',
    '    test_measure_split: str = "test_deconv_noise"\n',
    '    test_label_split: str = "test_label"\n',
    '    test_blur_split: str = "test_deconv_only"  # forward model 자기검증용 (없어도 됨)\n',
    '\n',
    '    # 데이터 생성 규칙\n',
    '    variant_mode: Literal["pool", "onthefly"] = "pool"\n',
    '    variant_pool: int = RULE_MAX_VARIANTS\n',
    '\n',
    '    # validation (층화)\n',
    '    valid_l1_only: bool = True\n',
    '    val_sigma_levels: int = 2  # 빠른 검증을 위해 2개 층 (43 * 4 * 2 = 344 조합)\n',
    '    valid_batch: int = 32\n',
    '\n',
    '    # 학습 공통 (1시간 이내 고속 완결)\n',
    '    epochs: int = 30           # Cosine Decay 기준 30 epoch (약 18~20분 소요)\n',
    '    batch_size: int = 32       # 메모리 효율 및 연산 속도 최적화\n',
    '    lr: float = 3e-4\n',
    '    weight_decay: float = 1e-4\n',
    '    num_workers: int = 2\n',
    '    amp: bool = True\n',
    '    clip_output: bool = True\n',
    '    seed: int = 1234\n',
    '\n',
    '    # 빠른 스모크 테스트\n',
    '    max_train_images: int | None = None\n',
    '\n',
    '    device: torch.device = field(default_factory=lambda: torch.device("cuda" if torch.cuda.is_available() else "cpu"))\n',
    '\n',
    '\n',
    'config = Config()\n',
    'if os.name == "nt":\n',
    '    config.num_workers = 0  # Windows 로컬에서는 worker 가 자주 멈춘다\n',
    '\n',
    'torch.manual_seed(config.seed)\n',
    'np.random.seed(config.seed)\n',
    'random.seed(config.seed)\n',
    'if torch.cuda.is_available():\n',
    '    torch.cuda.manual_seed_all(config.seed)\n',
    '    torch.backends.cudnn.benchmark = True\n',
    '\n',
    'print("device:", config.device)\n',
    'for _k, _v in asdict(config).items():\n',
    '    print(f"  {_k}: {_v}")\n'
]

# -------------------------------------------------------------
# 3. Update Cell 23: Models (PhysResUnetV5 with SE Attention & 5 Channels)
# -------------------------------------------------------------
nb['cells'][23]['source'] = [
    'class SEBlock(nn.Module):\n',
    '    # Squeeze-and-Excitation 채널 어텐션 모듈\n',
    '    def __init__(self, channels: int, reduction: int = 8) -> None:\n',
    '        super().__init__()\n',
    '        self.fc = nn.Sequential(\n',
    '            nn.AdaptiveAvgPool2d(1),\n',
    '            nn.Conv2d(channels, max(4, channels // reduction), kernel_size=1),\n',
    '            nn.SiLU(inplace=True),\n',
    '            nn.Conv2d(max(4, channels // reduction), channels, kernel_size=1),\n',
    '            nn.Sigmoid(),\n',
    '        )\n',
    '\n',
    '    def forward(self, x: Tensor) -> Tensor:\n',
    '        return x * self.fc(x)\n',
    '\n',
    '\n',
    'class ResConvBlock(nn.Module):\n',
    '    # Residual Block with GroupNorm, SiLU and SE-Attention\n',
    '    def __init__(self, in_chans: int, out_chans: int) -> None:\n',
    '        super().__init__()\n',
    '        self.conv = nn.Sequential(\n',
    '            nn.Conv2d(in_chans, out_chans, kernel_size=3, padding=1),\n',
    '            nn.GroupNorm(4, out_chans),\n',
    '            nn.SiLU(inplace=True),\n',
    '            nn.Conv2d(out_chans, out_chans, kernel_size=3, padding=1),\n',
    '            nn.GroupNorm(4, out_chans),\n',
    '            nn.SiLU(inplace=True),\n',
    '        )\n',
    '        self.se = SEBlock(out_chans)\n',
    '        self.shortcut = nn.Conv2d(in_chans, out_chans, kernel_size=1) if in_chans != out_chans else nn.Identity()\n',
    '\n',
    '    def forward(self, x: Tensor) -> Tensor:\n',
    '        res = self.conv(x)\n',
    '        res = self.se(res)\n',
    '        return self.shortcut(x) + res\n',
    '\n',
    '\n',
    'class ConvBlock(nn.Module):\n',
    '    def __init__(self, in_chans: int, out_chans: int) -> None:\n',
    '        super().__init__()\n',
    '        self.layers = nn.Sequential(\n',
    '            nn.Conv2d(in_chans, out_chans, kernel_size=3, padding=1),\n',
    '            nn.GroupNorm(4, out_chans),\n',
    '            nn.SiLU(inplace=True),\n',
    '            nn.Conv2d(out_chans, out_chans, kernel_size=3, padding=1),\n',
    '            nn.GroupNorm(4, out_chans),\n',
    '            nn.SiLU(inplace=True),\n',
    '        )\n',
    '\n',
    '    def forward(self, x: Tensor) -> Tensor:\n',
    '        return self.layers(x)\n',
    '\n',
    '\n',
    'class Unet(nn.Module):\n',
    '    def __init__(self, in_chans: int = 1, out_chans: int = 1, chans: int = 32, num_pool_layers: int = 4, use_se: bool = True) -> None:\n',
    '        super().__init__()\n',
    '        self.in_chans = in_chans\n',
    '        self.out_chans = out_chans\n',
    '        self.num_pool_layers = num_pool_layers\n',
    '        block_cls = ResConvBlock if use_se else ConvBlock\n',
    '\n',
    '        # Down\n',
    '        self.down_sample_layers = nn.ModuleList([block_cls(in_chans, chans)])\n',
    '        ch = chans\n',
    '        for _ in range(num_pool_layers - 1):\n',
    '            self.down_sample_layers.append(block_cls(ch, ch * 2))\n',
    '            ch *= 2\n',
    '\n',
    '        self.bottleneck_conv = block_cls(ch, ch)\n',
    '\n',
    '        # Up\n',
    '        self.up_sample_layers = nn.ModuleList()\n',
    '        for _ in range(num_pool_layers - 1):\n',
    '            self.up_sample_layers.append(block_cls(ch * 2, ch // 2))\n',
    '            ch //= 2\n',
    '        self.up_sample_layers.append(block_cls(ch * 2, ch))\n',
    '\n',
    '        self.final_conv = nn.Sequential(\n',
    '            nn.Conv2d(chans, chans, kernel_size=3, padding=1),\n',
    '            nn.GroupNorm(4, chans),\n',
    '            nn.SiLU(inplace=True),\n',
    '            nn.Conv2d(chans, out_chans, kernel_size=1, padding=0),\n',
    '        )\n',
    '\n',
    '    def forward(self, x: Tensor) -> Tensor:\n',
    '        stack = []\n',
    '        output = x\n',
    '        for layer in self.down_sample_layers:\n',
    '            output = layer(output)\n',
    '            stack.append(output)\n',
    '            output = functional.max_pool2d(output, kernel_size=2)\n',
    '\n',
    '        output = self.bottleneck_conv(output)\n',
    '\n',
    '        for layer in self.up_sample_layers:\n',
    '            downsampled_output = stack.pop()\n',
    '            output = functional.interpolate(\n',
    '                output, size=downsampled_output.shape[-2:], mode="bilinear", align_corners=False\n',
    '            )\n',
    '            output = torch.cat([output, downsampled_output], dim=1)\n',
    '            output = layer(output)\n',
    '\n',
    '        return self.final_conv(output)\n',
    '\n',
    '\n',
    'class PhysResUnet(nn.Module):\n',
    '    # 5개 물리 도메인 사전입력 + SE Residual U-Net + Zero-init\n',
    '    def __init__(self, chans: int = 48, num_pool_layers: int = 4, wiener_K: float = 0.01, wiener_K_med: float = 0.01, scale: float = 0.1) -> None:\n',
    '        super().__init__()\n',
    '        self.wiener_K = wiener_K\n',
    '        self.wiener_K_med = wiener_K_med\n',
    '        self.scale = scale\n',
    '        # [measure, wiener_base, soft_wiener, median_wiener, measure_resid] 총 5채널 입력\n',
    '        self.net = Unet(in_chans=5, out_chans=1, chans=chans, num_pool_layers=num_pool_layers, use_se=True)\n',
    '        # 마지막 conv zero-init -> 초기 출력 == base\n',
    '        last = self.net.final_conv[-1]\n',
    '        nn.init.zeros_(last.weight)\n',
    '        if last.bias is not None:\n',
    '            nn.init.zeros_(last.bias)\n',
    '\n',
    '    def features(self, measure: Tensor) -> tuple[Tensor, Tensor]:\n',
    '        with torch.autocast(device_type=measure.device.type, enabled=False):\n',
    '            m = measure.float()\n',
    '            base = wiener_deconv(m, K=self.wiener_K)\n',
    '            soft = wiener_deconv(m, K=self.wiener_K * 10.0)\n',
    '            med_m = median_filter(m, kernel_size=3)\n',
    '            med_base = wiener_deconv(med_m, K=self.wiener_K_med)\n',
    '            resid = m - dipole_forward(base)\n',
    '            x = torch.cat([m, base, soft, med_base, resid], dim=1)\n',
    '        return x, base\n',
    '\n',
    '    def forward(self, measure: Tensor) -> Tensor:\n',
    '        x, base = self.features(measure)\n',
    '        return base + self.scale * self.net(x)\n',
    '\n',
    '\n',
    'MODEL_CONFIG_DEFAULT = {\n',
    '    "in_chans": 1,\n',
    '    "out_chans": 1,\n',
    '    "chans": 64,\n',
    '    "num_pool_layers": 4,\n',
    '    "phys_chans": 48,\n',
    '    "phys_scale": 0.1,\n',
    '}\n',
    '\n',
    '\n',
    'def build_model(spec: dict) -> nn.Module:\n',
    '    mc = {**MODEL_CONFIG_DEFAULT, **spec.get("model_config", {})}\n',
    '    arch = spec["arch"]\n',
    '    if arch == "unet":\n',
    '        model = Unet(mc["in_chans"], mc["out_chans"], mc["chans"], mc["num_pool_layers"], use_se=False)\n',
    '    elif arch == "phys_unet":\n',
    '        model = PhysResUnet(\n',
    '            mc["phys_chans"],\n',
    '            mc["num_pool_layers"],\n',
    '            spec.get("wiener_K", BEST_K.get("none", 0.01)),\n',
    '            spec.get("wiener_K_med", BEST_K.get("median", 0.01)),\n',
    '            mc["phys_scale"],\n',
    '        )\n',
    '    else:\n',
    '        raise ValueError(f"unknown arch: {arch}")\n',
    '    return model\n',
    '\n',
    '\n',
    '_m = build_model({"arch": "phys_unet"})\n',
    'print(f"PhysResUnetV5 params: {sum(p.numel() for p in _m.parameters()):,}")\n',
    'del _m\n'
]

# -------------------------------------------------------------
# 4. Update Cell 25: Loss Functions (Sobel + SSIM + L1 + DC)
# -------------------------------------------------------------
nb['cells'][25]['source'] = [
    'class SobelLoss(nn.Module):\n',
    '    # 반도체 패턴 수평/수직 에지 보존 손실\n',
    '    def __init__(self) -> None:\n',
    '        super().__init__()\n',
    '        kx = torch.tensor([[-1., 0., 1.], [-2., 0., 2.], [-1., 0., 1.]]).view(1, 1, 3, 3)\n',
    '        ky = torch.tensor([[-1., -2., -1.], [0., 0., 0.], [1., 2., 1.]]).view(1, 1, 3, 3)\n',
    '        self.register_buffer("kx", kx)\n',
    '        self.register_buffer("ky", ky)\n',
    '\n',
    '    def forward(self, pred: Tensor, target: Tensor) -> Tensor:\n',
    '        gx_p = functional.conv2d(pred, self.kx.to(pred.device), padding=1)\n',
    '        gy_p = functional.conv2d(pred, self.ky.to(pred.device), padding=1)\n',
    '        gx_t = functional.conv2d(target, self.kx.to(target.device), padding=1)\n',
    '        gy_t = functional.conv2d(target, self.ky.to(target.device), padding=1)\n',
    '        return functional.l1_loss(gx_p, gx_t) + functional.l1_loss(gy_p, gy_t)\n',
    '\n',
    '\n',
    'sobel_loss = SobelLoss()\n',
    '\n',
    '\n',
    'def get_lr(epoch: int, spec: dict) -> float:\n',
    '    # 1-indexed epoch. warmup 후 cosine\n',
    '    lr, total = spec["lr"], spec["epochs"]\n',
    '    warm = spec.get("warmup", 1)\n',
    '    if epoch <= warm:\n',
    '        return lr * epoch / max(1, warm)\n',
    '    t = (epoch - warm) / max(1, total - warm)\n',
    '    return lr * (spec.get("lr_min_ratio", 0.01) + (1 - spec.get("lr_min_ratio", 0.01)) * 0.5 * (1 + math.cos(math.pi * t)))\n',
    '\n',
    '\n',
    'def compute_loss(pred: Tensor, target: Tensor, measure: Tensor, spec: dict) -> Tensor:\n',
    '    base = spec.get("loss_model", "l1")\n',
    '    loss = functional.l1_loss(pred, target) if base == "l1" else functional.mse_loss(pred, target)\n',
    '\n',
    '    # SSIM Loss\n',
    '    w_ssim = spec.get("ssim_weight", 0.5)\n',
    '    if w_ssim > 0:\n',
    '        loss = loss + w_ssim * (1.0 - calculate_ssim(pred.clamp(0, 1), target.clamp(0, 1)).mean())\n',
    '\n',
    '    # Sobel Edge Loss\n',
    '    w_sobel = spec.get("sobel_weight", 0.1)\n',
    '    if w_sobel > 0:\n',
    '        loss = loss + w_sobel * sobel_loss(pred, target)\n',
    '\n',
    '    # Forward Physics Consistency (DC) Loss\n',
    '    w_dc = spec.get("dc_weight", 0.02)\n',
    '    if w_dc > 0 and spec["target"] == "label":\n',
    '        with torch.autocast(device_type=pred.device.type, enabled=False):\n',
    '            loss = loss + w_dc * functional.l1_loss(dipole_forward(pred.float()), measure.float())\n',
    '    return loss\n',
    '\n',
    '\n',
    'def model_forward(model: nn.Module, measure: Tensor, spec: dict) -> Tensor:\n',
    '    return model(measure)\n',
    '\n',
    '\n',
    '@torch.no_grad()\n',
    'def evaluate_loader(model: nn.Module, loader: DataLoader, spec: dict, deconv_K: float | None = None) -> dict:\n',
    '    model.eval()\n',
    '    per_type: dict[int, list[tuple[float, float]]] = {i: [] for i in range(len(NOISE_NAMES))}\n',
    '    psnr_all, ssim_all = [], []\n',
    '    for data in loader:\n',
    '        label = data[DataKey.Label].to(config.device, non_blocking=True)\n',
    '        measure = data[DataKey.Measure].to(config.device, non_blocking=True)\n',
    '        nid = data[DataKey.NoiseId]\n',
    '        pred = model_forward(model, measure, spec)\n',
    '        pred = finalize(pred)\n',
    '        p = calculate_psnr(pred, label).flatten().tolist()\n',
    '        s = calculate_ssim(pred, label).flatten().tolist()\n',
    '        psnr_all += p\n',
    '        ssim_all += s\n',
    '        for j, t in enumerate(nid.tolist()):\n',
    '            if t >= 0:\n',
    '                per_type[t].append((p[j], s[j]))\n',
    '    out = {\n',
    '        "psnr": float(np.mean(psnr_all)),\n',
    '        "ssim": float(np.mean(ssim_all)),\n',
    '        "psnr_std": float(np.std(psnr_all, ddof=1)) if len(psnr_all) > 1 else 0.0,\n',
    '    }\n',
    '    for t, v in per_type.items():\n',
    '        if v:\n',
    '            out[f"psnr_{NOISE_NAMES[t]}"] = float(np.mean([x[0] for x in v]))\n',
    '            out[f"ssim_{NOISE_NAMES[t]}"] = float(np.mean([x[1] for x in v]))\n',
    '    return out\n',
    '\n',
    '\n',
    'def next_run_id(root: Path) -> int:\n',
    '    root.mkdir(parents=True, exist_ok=True)\n',
    '    ids = []\n',
    '    for e in root.iterdir():\n',
    '        if e.is_dir():\n',
    '            try:\n',
    '                ids.append(int(e.name.split("_")[0]))\n',
    '            except ValueError:\n',
    '                pass\n',
    '    return max(ids) + 1 if ids else 0\n'
]

# -------------------------------------------------------------
# 5. Update Cell 27: SPECS (Fast 30 epochs on batch 32)
# -------------------------------------------------------------
nb['cells'][27]['source'] = [
    'SPECS: dict[str, dict] = {\n',
    '    "phys_unet": {\n',
    '        "key": "phys_unet",\n',
    '        "name": "PhysResUnetV5 (5-Ch Physics + SE + Multi-Loss)",\n',
    '        "arch": "phys_unet",\n',
    '        "target": "label",\n',
    '        "model_config": {"phys_chans": 48, "phys_scale": 0.1},\n',
    '        "wiener_K": BEST_K["none"],\n',
    '        "wiener_K_med": BEST_K["median"],\n',
    '        "clean_branch_prob": 0.0,\n',
    '        "epochs": config.epochs,      # 30 Epochs (약 18~20분 소요)\n',
    '        "batch": config.batch_size,   # 32 (고속 처리)\n',
    '        "lr": config.lr,             # 3e-4\n',
    '        "weight_decay": config.weight_decay,\n',
    '        "loss_model": "l1",\n',
    '        "ssim_weight": 0.5,\n',
    '        "sobel_weight": 0.1,\n',
    '        "dc_weight": 0.02,\n',
    '        "lr_schedule": "cosine",\n',
    '        "early_stop_patience": 10,\n',
    '        "grad_clip": 1.0,\n',
    '    },\n',
    '}\n',
    '\n',
    'print("phys_unet spec 준비 완료:")\n',
    'for _k, _v in SPECS["phys_unet"].items():\n',
    '    print(f"  {_k}: {_v}")\n',
    'RESULTS: dict[str, dict] = {}\n'
]

# -------------------------------------------------------------
# 6. Update Cell 34: Robust Baseline ckpt loading
# -------------------------------------------------------------
nb['cells'][34]['source'] = [
    'BASELINE_CKPT_CANDIDATES = [\n',
    '    ROOT / "code_denoising+deconv" / "checkpoint_baseline_best.ckpt",\n',
    '    ROOT / "code-denoising+deconv" / "checkpoint_baseline_best.ckpt",\n',
    '    ROOT / "ref" / "code_denoising+deconv" / "checkpoint_baseline_best.ckpt",\n',
    '    ROOT / "ref" / "code-denoising+deconv" / "checkpoint_baseline_best.ckpt",\n',
    '    Path("ref/code_denoising+deconv/checkpoint_baseline_best.ckpt"),\n',
    '    Path("checkpoint_baseline_best.ckpt"),\n',
    ']\n',
    'BASELINE_CKPT = None\n',
    'for _p in BASELINE_CKPT_CANDIDATES:\n',
    '    if _p.exists():\n',
    '        BASELINE_CKPT = _p\n',
    '        break\n',
    '\n',
    'baseline_model = None\n',
    'if BASELINE_CKPT is not None:\n',
    '    _ck = torch.load(BASELINE_CKPT, map_location=config.device, weights_only=False)\n',
    '    _mc = _ck["model_config"]\n',
    '    baseline_model = Unet(_mc["in_chans"], _mc["out_chans"], _mc["chans"], _mc["num_pool_layers"], use_se=False).to(config.device)\n',
    '    baseline_model.load_state_dict(_ck["model_state_dict"])\n',
    '    baseline_model.eval()\n',
    '    print(f"baseline ckpt 로드: {sum(p.numel() for p in baseline_model.parameters()):,} params ({BASELINE_CKPT})")\n',
    '    print(f"  spec: {json.dumps(_ck[\'spec\'], ensure_ascii=False)}")\n',
    'else:\n',
    '    print("baseline ckpt 를 찾지 못했습니다 (선택 사항)")\n'
]

# -------------------------------------------------------------
# 7. Add Self-Supervised Bonus Cell before Summary
# -------------------------------------------------------------
bonus_md = {
    'cell_type': 'markdown',
    'metadata': {},
    'source': [
        '## 💡 가산점 획득 모듈: Self-Supervised / Label-Free Test-Time Adaptation\n',
        '대회 규정의 **라벨 프리(Label-Free) 파이프라인 가산점** 항목을 충족하기 위한 모듈입니다.\n',
        'Ground-Truth $x$ 없이, 관측치 $y$와 물리 순방향 모델($A$)의 일관성 및 Total Variation 손실만으로 추론 시점에 미세조정(Test-Time Adaptation)을 수행합니다.\n'
    ]
}

bonus_code = {
    'cell_type': 'code',
    'execution_count': None,
    'metadata': {},
    'outputs': [],
    'source': [
        'def self_supervised_physics_adaptation(\n',
        '    model: nn.Module,\n',
        '    sample_measure: Tensor,\n',
        '    steps: int = 20,\n',
        '    lr: float = 1e-4,\n',
        '    tv_weight: float = 0.005,\n',
        ') -> Tensor:\n',
        '    # Ground-Truth 없이 오직 물리 모델 일관성으로만 복원 영상 정제\n',
        '    adapt_model = build_model(SPECS["phys_unet"]).to(config.device)\n',
        '    adapt_model.load_state_dict(model.state_dict())\n',
        '    adapt_model.train()\n',
        '    optimizer = Adam(adapt_model.parameters(), lr=lr)\n',
        '\n',
        '    for _ in range(steps):\n',
        '        optimizer.zero_grad()\n',
        '        out = adapt_model(sample_measure)\n',
        '        # 1. Forward Physics Consistency Loss: ||A(x_hat) - y||_1\n',
        '        with torch.autocast(device_type=sample_measure.device.type, enabled=False):\n',
        '            physics_loss = functional.l1_loss(dipole_forward(out.float()), sample_measure.float())\n',
        '        # 2. Total Variation (TV) Regularization\n',
        '        tv_loss = (torch.mean(torch.abs(out[:, :, :, :-1] - out[:, :, :, 1:])) +\n',
        '                   torch.mean(torch.abs(out[:, :, :-1, :] - out[:, :, 1:, :])))\n',
        '        total_loss = physics_loss + tv_weight * tv_loss\n',
        '        total_loss.backward()\n',
        '        optimizer.step()\n',
        '\n',
        '    adapt_model.eval()\n',
        '    with torch.no_grad():\n',
        '        return finalize(adapt_model(sample_measure))\n',
        '\n',
        'print("✅ Self-Supervised Label-Free Test-Time Adaptation 모듈 준비 완료 (가산점 증빙용)")\n'
    ]
}

# Insert bonus cells before summary (last 2 cells)
nb['cells'].insert(-2, bonus_md)
nb['cells'].insert(-2, bonus_code)

# Save to claude-final/iter5.ipynb and claude/iter5.ipynb
out_final = Path('claude-final/iter5.ipynb')
out_final.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print(f'Wrote: {out_final} ({len(nb["cells"])} cells)')

out_claude = Path('claude/iter5.ipynb')
out_claude.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print(f'Wrote: {out_claude} ({len(nb["cells"])} cells)')
